module.exports = [
  {
    id: 1,
    name: "مایو حرفه‌ای نایک",
    price: "450,000",
    password: "123456",
    inStock: true,
  },
  {
    id: 2,
    name: "مایو اسپیدو ضد کلر",
    price: "380,000",
    password: "esdbrf",
    inStock: true,
  },
  {
    id: 3,
    name: "مایو آرنا مسابقات",
    price: "520,000",
    password: "fdbdfb",
    inStock: false,
  },
  {
    id: 4,
    name: "مایو کودکان رنگی",
    price: "280,000",
    password: "12asf3456",
    inStock: true,
  },
  {
    id: 5,
    name: "عینک شنا اسپیدو",
    price: "180,000",
    password: "dgbfgn",
    inStock: true,
  },
  {
    id: 6,
    name: "عینک آرنا حرفه‌ای",
    price: "220,000",
    password: "3654654",
    inStock: true,
  },
  {
    id: 7,
    name: "عینک کودکان",
    price: "120,000",
    password: "wqrcv",
    inStock: true,
  },

  {
    id: 12,
    name: " فین اسپیدو",
    price: "850,000",
    password: "23r235",
    inStock: true,
  },
  {
    id: 13,
    name: " فین میسیسیپی",
    price: "450,000",
    password: "23r235",
    inStock: false,
  },

  {
    id: 8,
    name: "  کیف شنا نایک",
    price: "85,000",
    password: "235r42",
    inStock: true,
  },
  {
    id: 9,
    name: "کیف شنا اسپیدو",
    price: "45,000",
    password: "dasv",
    inStock: true,
  },
  {
    id: 10,
    name: " کلاه شناحرفه ای",
    price: "150,000",
    password: "sdvsdv",
    inStock: true,
  },
  {
    id: 11,
    name: "کلاه شنا اسپیدو",
    price: "85,000",
    password: "erbvgrse",
    inStock: true,
  },
];
